<?php
defined('LABS_TABLE') || define('LABS_TABLE', 'labs');
defined('LAB_ID') || define('LAB_ID', 'lab_id');
defined('LAB_NAME') || define('LAB_NAME', 'lab_name');
defined('LAB_DES') || define('LAB_DES', 'lab_des');
defined('LAB_IMG') || define('LAB_IMG', 'lab_img');
defined('LAB_PRICE') || define('LAB_PRICE', 'lab_price');
defined('LAB_UID') || define('LAB_UID', 'lab_uid');
defined('LAB_UNAME') || define('LAB_UNAME', 'lab_uname');
defined('LAB_STATUS') || define('LAB_STATUS', 'lab_status');
defined('LAB_STATUS_ADMIN') || define('LAB_STATUS_ADMIN', 'lab_status_admin');
defined('LAB_STATUS_VERSION') || define('LAB_STATUS_VERSION', 'lab_status_version');
defined('LAB_ARTICLE') || define('LAB_ARTICLE', 'lab_article');
defined('LAB_TIME') || define('LAB_TIME', 'lab_time');
defined('LAB_UNIT') || define('LAB_UNIT', 'lab_unit');
defined('LAB_WEIGHT') || define('LAB_WEIGHT', 'lab_weight');
defined('LAB_SUBJECT') || define('LAB_SUBJECT', 'lab_subject');
defined('LAB_UPDATE') || define('LAB_UPDATE', 'lab_update');
defined('LAB_LAST_VERSION') || define('LAB_LAST_VERSION', 'lab_last_version');